I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1242, in script
    leblanc "Yes?"
Exception: Sayer 'leblanc' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1242, in script
    leblanc "Yes?"
  File "C:\Users\CIIT_1\Downloads\renpy-7.2.2-sdk\renpy\ast.py", line 664, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\CIIT_1\Downloads\renpy-7.2.2-sdk\renpy\ast.py", line 564, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'leblanc' is not defined.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Animatronic 1.0
Fri May 10 11:58:22 2019
